name: GitHub - Build Simulation Images
on:
  workflow_dispatch:
  # schedule:
  # - cron:  '0 3 * * 1,3,6'
jobs:
  build:
    name: "Simulation Image Generation"
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v3
      with:                                                                                           
        fetch-depth: 0
    - name: List Tags
      run: git tag
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get Cosmodrome
      run: |
        wget https://github.com/robolaunch/cosmodrome/releases/download/v0.1.0-alpha.12/cosmodrome-amd64;
        chmod +x cosmodrome-amd64;
        mv cosmodrome-amd64 /usr/local/bin/cosmodrome;
        cosmodrome --help
    
    - name: Build CARLA Image 
      run: cosmodrome launch --config pipelines/simulation/carla.yaml
    
    - name: Build Unity (hub) Image 
      run: cosmodrome launch --config pipelines/simulation/unity3d.yaml